"""Generate ESPHome's required YAML from root Hoast config and root .env."""

import argparse
import ipaddress
import json
import logging
import os
import subprocess
from pathlib import Path

from dotenv import dotenv_values

from hoast.config import load_config

LOGGER = logging.getLogger(__name__)
GENERATED_MARKER = "# Generated from root config.toml and .env; do not edit.\n"


def active_ssid() -> str:
    """Return the sole active Wi-Fi AP SSID reported by NetworkManager.

    Raises:
        RuntimeError: If no uniquely active SSID is present.

    """
    result = subprocess.run(
        ["nmcli", "-t", "-f", "IN-USE,SSID", "dev", "wifi"],
        capture_output=True, text=True, check=True,
    )
    active = [line.partition(":")[2] for line in result.stdout.splitlines() if line.startswith("*:")]
    if len(active) != 1 or not active[0]:
        raise RuntimeError("Expected one active Wi-Fi AP with an SSID")
    return active[0]


def ap_host_address(device_host: str) -> str:
    """Return the host AP address used to reach the configured ESP device.

    Args:
        device_host:
            ESP hostname or IPv4 address from root [satellite].host.

    Returns:
        IPv4 source address from the host route to the ESP, used for NTP.

    Raises:
        ValueError: If routing does not yield exactly one IPv4 source address.

    """
    result = subprocess.run(
        ["ip", "-j", "-4", "route", "get", device_host],
        capture_output=True, text=True, check=True,
    )
    routes = json.loads(result.stdout)
    if not isinstance(routes, list) or len(routes) != 1 or "prefsrc" not in routes[0]:
        raise ValueError("Could not determine the AP host address for NTP")
    return str(ipaddress.IPv4Address(routes[0]["prefsrc"]))


def write_secrets(path: Path, config: Path, env_file: Path) -> None:
    """Refresh an ignored ESPHome build artifact from the two root config sources.

    Args:
        path:
            Generated mode-0600 YAML read by ESPHome's !secret directives.

        config:
            Root Hoast TOML specifying the satellite endpoint.

        env_file:
            Root dotenv holding Wi-Fi, Noise API and OTA credentials.

    Raises:
        ValueError: If the endpoint or required credentials are missing.

        FileExistsError: If an existing YAML was not generated by this helper.

    """
    settings = load_config(config)
    if settings.satellite is None:
        raise ValueError("Configure [satellite].host before preparing ESPHome")
    source = dotenv_values(env_file, interpolate=False)
    names = {
        "wifi_password": "RESPEAKER_WIFI_PASSWORD",
        "api_key": "ESPHOME_API_KEY",
        "ota_password": "ESPHOME_OTA_PASSWORD",
    }
    values: dict[str, str] = {
        "wifi_ssid": active_ssid(),
        "ntp_host": ap_host_address(settings.satellite.host),
    }
    for target, name in names.items():
        value = source.get(name)
        if not isinstance(value, str) or not value or "\n" in value or "\r" in value:
            raise ValueError(f"Set {name} in the root .env")
        values[target] = value
    contents = GENERATED_MARKER + "".join(
        f"{key}: {json.dumps(value)}\n" for key, value in values.items()
    )
    if path.exists():
        existing = path.read_text()
        if not existing.startswith(GENERATED_MARKER):
            raise FileExistsError("ESPHome secrets.yaml must be generated from root settings")
        if existing == contents:
            LOGGER.info("prepare.secrets status=unchanged")
            return
    temporary = path.with_name(path.name + ".tmp")
    fd = os.open(temporary, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    with os.fdopen(fd, "w") as output:
        output.write(contents)
    os.replace(temporary, path)
    LOGGER.info("prepare.secrets status=updated source=root")


def main() -> None:
    """Create ESPHome's build artifact without logging any credentials."""
    parser = argparse.ArgumentParser(description="Generate ESPHome secrets from root settings")
    parser.add_argument("--config", type=Path, default=Path("config.toml"))
    parser.add_argument("--env-file", type=Path, default=Path(".env"))
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO)
    write_secrets(Path(__file__).resolve().parent.parent / "secrets.yaml", args.config, args.env_file)


if __name__ == "__main__":
    main()
